# -*- coding: utf-8 -*-
"""distributed_gene_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hrgqLoj9R-IuR1WWkt2TJI24q6fx5yJr
"""

from mpi4py import MPI
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
import numpy as np

comm = MPI.COMM_WORLD
rank = comm.Get_rank()
size = comm.Get_size()

if rank == 0:
    df = pd.read_csv('leukemia_expression.csv')

    data   = df.iloc[:, :-1].values
    target = df.iloc[:, -1].values
else:
    data = target = None

data   = comm.bcast(data,   root=0)
target = comm.bcast(target, root=0)

chunk = len(data) // size
start = rank * chunk
end   = start + chunk if rank != size-1 else len(data)

clf = RandomForestClassifier(n_estimators=100)
clf.fit(data[start:end], target[start:end])
score = clf.score(data[start:end], target[start:end])
scores = comm.gather(score, root=0)

if rank == 0:
    print('Bioinformatics scores from all nodes:', scores)
    print('Average score:', np.mean(scores))