# -*- coding: utf-8 -*-
"""distributed_mnist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hrgqLoj9R-IuR1WWkt2TJI24q6fx5yJr
"""

from mpi4py import MPI
from sklearn.datasets import load_digits
from sklearn.ensemble import RandomForestClassifier
import numpy as np

comm = MPI.COMM_WORLD
rank = comm.Get_rank()
size = comm.Get_size()

if rank == 0:
    digits = load_digits()
    data, target = digits.data, digits.target
else:
    data = target = None

data   = comm.bcast(data,   root=0)
target = comm.bcast(target, root=0)

chunk = len(data) // size
start = rank * chunk
end   = start + chunk if rank != size-1 else len(data)

clf = RandomForestClassifier(n_estimators=100)
clf.fit(data[start:end], target[start:end])
score = clf.score(data[start:end], target[start:end])

scores = comm.gather(score, root=0)
if rank == 0:
    print('Scores from all nodes:', scores)
    print('Average score:', np.mean(scores))